name: Deploy Lambda
on:
  push:
    branches:
      - main
jobs:
  build-source:
    name: build lambda
    strategy:
      matrix:
        python-version: [3.10.12]
        aws_region: [eu-west-2]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        env:
          CI: true
      - name: Bundle
        uses: montudor/action-zip@v1.0.0
        with:
          args: zip -qq -r ./bundle.zip ./

  deploy-source:
    name: deploy lambda
    needs: build-source
    strategy:
      matrix:
        python-version: [3.10.12]
        aws_region: [eu-west-2]
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: appleboy/lambda-action@v0.1.9
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: "eu-west-2"
          function_name: newOrderHandler
          zip_file: bundle.zip
          layers: arn:aws:lambda:eu-west-2:819524876098:layer:python-layer:2
          description: ${{steps.tag.outputs.tag}}
